export default {
    // MIDDLEWARE
    ADD_PRODUCT_TO_BASKET: "ADD_PRODUCT_TO_BASKET",
    DELETE_PRODUCT_FROM_BASKET: "DELETE_PRODUCT_FROM_BASKET",
    PRODUCT_SEARCH: "PRODUCT_SEARCH",

    // REDUCERS
    MAIN_ERROR: "MAIN_ERROR",
    PRODUCT_FOUND: "PRODUCT_FOUND",
    NEW_PRODUCT_IN_A_BASKET: "NEW_PRODUCT_IN_A_BASKET"
};
